name: Sara Bee
url: http://sarabee.github.io/
description: Some words and things
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "/blog/page:num/"
collections:
    projects:
        output: true

plugins: [jekyll-paginate]
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
